-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 19:06:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeID` CHAR(10) NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Tel` VARCHAR(10) NULL,
  `Address` VARCHAR(100) NULL,
  `TypeEmp` VARCHAR(20) NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Depaetment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Depaetment` (
  `DeptID` CHAR(10) NOT NULL,
  `DeptName` VARCHAR(45) NULL,
  PRIMARY KEY (`DeptID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BelongTo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BelongTo` (
  `StartDate` DATETIME NOT NULL,
  `Status` DATETIME NULL,
  `Depaetment_DeptID` CHAR(10) NOT NULL,
  `Employee_EmployeeID` CHAR(10) NOT NULL,
  PRIMARY KEY (`Depaetment_DeptID`, `Employee_EmployeeID`),
  INDEX `fk_BelongTo_Employee1_idx` (`Employee_EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_BelongTo_Depaetment`
    FOREIGN KEY (`Depaetment_DeptID`)
    REFERENCES `mydb`.`Depaetment` (`DeptID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BelongTo_Employee1`
    FOREIGN KEY (`Employee_EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`account` (
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `AccountType` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`UserName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`customer` (
  `CustomerID` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(100) NULL DEFAULT NULL,
  `Contact` VARCHAR(45) NULL DEFAULT NULL,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `account_UserName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`, `account_UserName`),
  INDEX `fk_customer_account1_idx` (`account_UserName` ASC) VISIBLE,
  CONSTRAINT `fk_customer_account1`
    FOREIGN KEY (`account_UserName`)
    REFERENCES `project`.`account` (`UserName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`order` (
  `OrderID` CHAR(10) NOT NULL,
  `OrderDate` DATETIME NULL DEFAULT NULL,
  `TableNo` INT(11) NULL DEFAULT NULL,
  `OrderStatus` VARCHAR(45) NULL DEFAULT NULL,
  `OrderType` VARCHAR(45) NULL DEFAULT NULL,
  `customer_CustomerID` VARCHAR(20) NOT NULL,
  `Employee_EmployeeID` CHAR(10) NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_order_customer1_idx` (`customer_CustomerID` ASC) VISIBLE,
  INDEX `fk_order_Employee1_idx` (`Employee_EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_CustomerID`)
    REFERENCES `project`.`customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_Employee1`
    FOREIGN KEY (`Employee_EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`bill` (
  `Bill_ID` VARCHAR(10) NOT NULL,
  `BillDate` DATETIME NULL DEFAULT NULL,
  `BillName` VARCHAR(45) NULL DEFAULT NULL,
  `TotalPrice` INT(11) NULL DEFAULT NULL,
  `order_OrderID` CHAR(10) NOT NULL,
  INDEX `fk_bill_order1_idx` (`order_OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_bill_order1`
    FOREIGN KEY (`order_OrderID`)
    REFERENCES `project`.`order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`menucatalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`menucatalog` (
  `id_menucatalog` CHAR(10) NOT NULL,
  `name_menucatalog` VARCHAR(45) NULL DEFAULT NULL,
  `detail_menucatalog` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_menucatalog`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`promotion` (
  `id_promotion` CHAR(10) NOT NULL,
  `start_promotion` DATETIME NULL DEFAULT NULL,
  `end_promotion` DATETIME NULL DEFAULT NULL,
  `name_promotion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_promotion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`menu` (
  `id_menucatalog` CHAR(10) NULL DEFAULT NULL,
  `id_menu` CHAR(10) NOT NULL,
  `name_tha_menu` VARCHAR(45) NULL DEFAULT NULL,
  `name_eng_menu` VARCHAR(45) NULL DEFAULT NULL,
  `imge_menu` VARCHAR(2000) NULL DEFAULT NULL,
  `status_menu` VARCHAR(45) NULL DEFAULT NULL,
  `promotion_id_promotion` CHAR(10) NOT NULL,
  `Depaetment_DeptID` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_menu`, `Depaetment_DeptID`),
  INDEX `id_menucatalog` (`id_menucatalog` ASC) VISIBLE,
  INDEX `fk_menu_promotion1_idx` (`promotion_id_promotion` ASC) VISIBLE,
  INDEX `fk_menu_Depaetment1_idx` (`Depaetment_DeptID` ASC) VISIBLE,
  CONSTRAINT `Fk_menucatalog`
    FOREIGN KEY (`id_menucatalog`)
    REFERENCES `project`.`menucatalog` (`id_menucatalog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_promotion1`
    FOREIGN KEY (`promotion_id_promotion`)
    REFERENCES `project`.`promotion` (`id_promotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_Depaetment1`
    FOREIGN KEY (`Depaetment_DeptID`)
    REFERENCES `mydb`.`Depaetment` (`DeptID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`menudetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`menudetail` (
  `id_menu` CHAR(10) NULL DEFAULT NULL,
  `id_menudetail` CHAR(10) NOT NULL,
  `type_menudetail` VARCHAR(45) NULL DEFAULT NULL,
  `price_menudetail` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_menudetail`),
  INDEX `id_menu` (`id_menu` ASC) VISIBLE,
  CONSTRAINT `Fk_memu`
    FOREIGN KEY (`id_menu`)
    REFERENCES `project`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project`.`orderdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`orderdetail` (
  `OrderAmount` INT(11) NOT NULL,
  `MenuStatus` VARCHAR(45) NULL DEFAULT NULL,
  `Price` INT(11) NULL DEFAULT NULL,
  `discount` INT(11) NULL DEFAULT NULL,
  `order_OrderID` CHAR(10) NOT NULL,
  PRIMARY KEY (`OrderAmount`, `order_OrderID`),
  INDEX `fk_orderdetail_order1_idx` (`order_OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_orderdetail_order1`
    FOREIGN KEY (`order_OrderID`)
    REFERENCES `project`.`order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
